### ISSUE TITLE
[Enigma] Снова ключи

### ISSUE THREAD

**Issue by pavel-b-novikov** [dkondyrev/nsudotnet#4]
Я так понимаю, что вы не совсем в курсе что такое base64. Давайте-ка вы быстренько узнаете что это такое и расскажете мне для проверки.

**Comment by dkondyrev** [comment]
Base64 - способ кодирования, который переводит исходное сообщение в набор символов ASCII A-Z, a-z, 0-9 и еще двух символов. Позволяет представлять бинарные данные в виде текста. Не совсем понял, в чем проблема моей реализации.

**Comment by pavel-b-novikov** [comment]
BitConverter вам зачем тогда блин?

**Comment by dkondyrev** [comment]
Чтобы перевести длины ключа и вектора в массивы байт.

**Comment by pavel-b-novikov** [comment]
ЗАЧЕМ?!

2016-05-23 0:23 GMT+06:00 Dmitriy Kondyrev notifications@github.com:

> Чтобы перевести длины ключа и вектора в массивы байт.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/dkondyrev/nsudotnet/issues/4#issuecomment-220847603

## 

Sincerely yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by dkondyrev** [comment]
Ну я записываю в файл ключей сначала длину ключа, потом сам ключ. Тоже самое с вектором. При считывании читаю сначала длину, потом сам ключ

**Comment by pavel-b-novikov** [comment]
И зачем вы это делаете если у вас ключ в base64 и известно что на одной строке только один ключ?

**Comment by dkondyrev** [comment]
Я записываю в одну строку и вектор и ключ. Если записывать как разные строки, то длина действительно не нужна.

**Comment by pavel-b-novikov** [comment]
Вот это мне и не нравится в вашей реализации. При том не у вас одного - вместо того чтобы сделать проще - вы намеренно делаете сложнее.
Признавайтесь теперь - вы кому-либо советовали этот способ, или вы у кого-то списали? Потому что таких примеров садомазохизма при проверке я уже видел штуки 4.

**Comment by dkondyrev** [comment]
Да нет, не списывал и не советовал. Просто я не сразу заметил в условиях требование переводить все в base64 и изначально писал сырые байты, для чего и использовал длину. А когда переделал все с учетом этого требования, остались особенности изначальной реализации
